###########################################################################
### Server 설정
###########################################################################
server:
  servlet:
    context-path: /${spring.application.root}

###########################################################################
### Spring 설정
###########################################################################
spring:
  application:
    root: nas
    name: nas-api

  datasource:
    url: ENC(fxwK2fXAyRsYuLbBAozqJR3qWH8CGznquFQVjRtTPeDAETOn4nHanMhdi6DLcrX8K0PHcr4IXoe1xAlg9p1Z0h24dch4iaBmtcKO+/5x094=)
    username: ENC(beDx2gXAeAxV+VZd/SkiqMaczaTm3Rj2l0TpY8ogShokNlnu6tVAdjmdpC7o1aSC)
    password: ENC(4SyrWZHyzfkDQqeynwC4NEiGEME4hSF5EDy6TcXnQ864Fuggclf00RrBFbWYu9m0)

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

###########################################################################
### log config 위치 설정
###########################################################################
logging:
  config: classpath:logback/spring-logback.xml

###########################################################################
### mybatis 설정
###########################################################################
mybatis:
  type-aliases-package: org.nas.api
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mapper/**/*Mapper.xml

###########################################################################
### Swagger 설정
###########################################################################
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true

  swagger-ui:
    path: /
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: list

  cache:
    disabled: true

  override-with-generic-response: false
  model-and-view-allowed: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

###########################################################################
### jasypt 설정
###########################################################################
jasypt:
  encryptor:
    password: ${ENCRYPTOR_PROFILE}

###########################################################################
### File Path 설정
###########################################################################
file:
  path:
    base-path: /attachfile
    base-path-dev: C:/dev/attachfile
    temp-base-path: /data/upload-temp
    thumbnail-base-path: upload-thumbnail
    ffmpeg-path: C:\Users\Lee_SH\Desktop\Dev\ffmpeg-2026-01-29-git-c898ddb8fe-full_build\bin\ffmpeg
